### ISSUE TITLE
Some problems identified while doing template-guided coordinate generation

### ISSUE THREAD

**Issue by greglandrum** [schrodinger/coordgenlibs#57]
The attached zip file contains a set of SDFs where I noticed either problems caused by using a template when generating coordinates or the coordinates not honoring the template. In each SDF the first molecule is the template (with the coordinates I used). The other molecules have the coordgen-coordinates created using template alignment

These were all generated using the RDKit's coordgen integration and coordgen v1.3.2

The molecules are all from ChEMBL.

Here's an example where using the template has somehow resulted in bad coordinates for a couple of molecules (this is doc16404):
![image](https://user-images.githubusercontent.com/540511/75783626-26a85b80-5d61-11ea-8694-61471f8cba0d.png)

And here's an example where it looks like rotatable bonds in the template are being perturbed to remove clashes (this is doc66014)
![image](https://user-images.githubusercontent.com/540511/75783727-4dff2880-5d61-11ea-9037-dec8cd4f8b19.png)

[cg_problems.zip](https://github.com/schrodinger/coordgenlibs/files/4281660/cg_problems.zip)

**Comment by d-b-w** [comment]
@rachelnwalker -
Do we think this is fixed by your recent work on template-guided minimization?

**Comment by rachelnwalker** [comment]
A few of the examples that Greg gave seem to be fixed (no clashes and RMSD between all the mols and the scaffold is < .2), including doc16404:

<img width="851" alt="ex1" src="https://user-images.githubusercontent.com/39069546/121756613-f741dc00-cad7-11eb-8d83-78b355597e37.png">

However, doc55715, doc66014, and doc105103 are still not aligning well with the template:

<img width="461" alt="Screen Shot 2021-06-11 at 5 14 46 PM" src="https://user-images.githubusercontent.com/39069546/121756782-88b14e00-cad8-11eb-9ea4-13ac705db4d6.png">

<img width="457" alt="Screen Shot 2021-06-11 at 5 15 04 PM" src="https://user-images.githubusercontent.com/39069546/121756800-98c92d80-cad8-11eb-96f4-0e28e39a6ec5.png">

<img width="447" alt="Screen Shot 2021-06-11 at 5 16 18 PM" src="https://user-images.githubusercontent.com/39069546/121756845-beeecd80-cad8-11eb-9176-2fda12a592ea.png">
